#GUI Template
#Author: Mehmet Akbulut
#MIT License
#Created using PySide and Qt Creator

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Sun Apr 24 16:38:16 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #Setup templates for all UI objects
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 448)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        MainWindow.setDocumentMode(False)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setWeight(75)
        font.setBold(True)
        self.centralWidget.setFont(font)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_Q2 = QtGui.QLabel(self.centralWidget)
        self.label_Q2.setObjectName("label_Q2")
        self.gridLayout.addWidget(self.label_Q2, 0, 1, 1, 1)
        self.label_Q1 = QtGui.QLabel(self.centralWidget)
        self.label_Q1.setObjectName("label_Q1")
        self.gridLayout.addWidget(self.label_Q1, 0, 0, 1, 1)
        self.label_Q3 = QtGui.QLabel(self.centralWidget)
        self.label_Q3.setObjectName("label_Q3")
        self.gridLayout.addWidget(self.label_Q3, 1, 0, 1, 1)
        self.label_Q4 = QtGui.QLabel(self.centralWidget)
        self.label_Q4.setObjectName("label_Q4")
        self.gridLayout.addWidget(self.label_Q4, 1, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 140)
        self.gridLayout.setColumnMinimumWidth(1, 140)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.line_2 = QtGui.QFrame(self.centralWidget)
        self.line_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.line_2.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(100, 100, 100);")
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setContentsMargins(-1, 6, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_internet = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_internet.setFont(font)
        self.label_internet.setObjectName("label_internet")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_internet)
        self.label_internetO = QtGui.QLabel(self.centralWidget)
        self.label_internetO.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_internetO.setObjectName("label_internetO")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_internetO)
        self.label_ros = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_ros.setFont(font)
        self.label_ros.setObjectName("label_ros")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_ros)
        self.label_rosO = QtGui.QLabel(self.centralWidget)
        self.label_rosO.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_rosO.setObjectName("label_rosO")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_rosO)
        self.label_charger = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_charger.setFont(font)
        self.label_charger.setObjectName("label_charger")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_charger)
        self.label_chargerO = QtGui.QLabel(self.centralWidget)
        self.label_chargerO.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_chargerO.setObjectName("label_chargerO")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_chargerO)
        self.label_mechanism = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_mechanism.setFont(font)
        self.label_mechanism.setObjectName("label_mechanism")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_mechanism)
        self.label_mechanismO = QtGui.QLabel(self.centralWidget)
        self.label_mechanismO.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_mechanismO.setObjectName("label_mechanismO")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_mechanismO)
        self.label_drone = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_drone.setFont(font)
        self.label_drone.setObjectName("label_drone")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_drone)
        self.label_droneO = QtGui.QLabel(self.centralWidget)
        self.label_droneO.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_droneO.setObjectName("label_droneO")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_droneO)
        self.label_dronebattery = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_dronebattery.setFont(font)
        self.label_dronebattery.setObjectName("label_dronebattery")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_dronebattery)
        self.label_dronebatteryO = QtGui.QLabel(self.centralWidget)
        self.label_dronebatteryO.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_dronebatteryO.setObjectName("label_dronebatteryO")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_dronebatteryO)
        self.label_dronecell1 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_dronecell1.setFont(font)
        self.label_dronecell1.setObjectName("label_dronecell1")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_dronecell1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_dronecell1O = QtGui.QLabel(self.centralWidget)
        self.label_dronecell1O.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_dronecell1O.setObjectName("label_dronecell1O")
        self.horizontalLayout_4.addWidget(self.label_dronecell1O)
        self.label_dronecell2O = QtGui.QLabel(self.centralWidget)
        self.label_dronecell2O.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_dronecell2O.setObjectName("label_dronecell2O")
        self.horizontalLayout_4.addWidget(self.label_dronecell2O)
        self.label_dronecell3O = QtGui.QLabel(self.centralWidget)
        self.label_dronecell3O.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_dronecell3O.setObjectName("label_dronecell3O")
        self.horizontalLayout_4.addWidget(self.label_dronecell3O)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_elapsed = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_elapsed.setFont(font)
        self.label_elapsed.setObjectName("label_elapsed")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_elapsed)
        self.label_uptime = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_uptime.setFont(font)
        self.label_uptime.setObjectName("label_uptime")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_uptime)
        self.label_elapsedO = QtGui.QLabel(self.centralWidget)
        self.label_elapsedO.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_elapsedO.setObjectName("label_elapsedO")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.label_elapsedO)
        self.label_uptimeO = QtGui.QLabel(self.centralWidget)
        self.label_uptimeO.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_uptimeO.setObjectName("label_uptimeO")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.label_uptimeO)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.line.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(100, 100, 100);")
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.label_status = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_4.addWidget(self.label_status)
        self.label_network = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_network.sizePolicy().hasHeightForWidth())
        self.label_network.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_network.setFont(font)
        self.label_network.setObjectName("label_network")
        self.verticalLayout_4.addWidget(self.label_network)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.push_autostart = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_autostart.sizePolicy().hasHeightForWidth())
        self.push_autostart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.push_autostart.setFont(font)
        self.push_autostart.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.push_autostart.setFlat(False)
        self.push_autostart.setObjectName("push_autostart")
        self.verticalLayout_5.addWidget(self.push_autostart)
        self.push_stop = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_stop.sizePolicy().hasHeightForWidth())
        self.push_stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.push_stop.setFont(font)
        self.push_stop.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.push_stop.setObjectName("push_stop")
        self.verticalLayout_5.addWidget(self.push_stop)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.push_charge = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_charge.sizePolicy().hasHeightForWidth())
        self.push_charge.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.push_charge.setFont(font)
        self.push_charge.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.push_charge.setObjectName("push_charge")
        self.verticalLayout_6.addWidget(self.push_charge)
        self.push_discharge = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_discharge.sizePolicy().hasHeightForWidth())
        self.push_discharge.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.push_discharge.setFont(font)
        self.push_discharge.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.push_discharge.setObjectName("push_discharge")
        self.verticalLayout_6.addWidget(self.push_discharge)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.push_catch = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_catch.sizePolicy().hasHeightForWidth())
        self.push_catch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.push_catch.setFont(font)
        self.push_catch.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.push_catch.setObjectName("push_catch")
        self.verticalLayout_8.addWidget(self.push_catch)
        self.push_release = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_release.sizePolicy().hasHeightForWidth())
        self.push_release.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.push_release.setFont(font)
        self.push_release.setStyleSheet("background-color: rgb(170, 85, 127);")
        self.push_release.setObjectName("push_release")
        self.verticalLayout_8.addWidget(self.push_release)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        #Fill in the created template UI objects
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "The Cage Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Q2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Q2</span></p><p align=\"center\"><span style=\" font-weight:600;\">FSR: </span><span style=\" color:#ffff00;\">!!v</span></p><p align=\"center\"><span style=\" font-weight:600;\">LSO: </span><span style=\" color:#ffff00;\">!!  </span><span style=\" font-weight:600;\">LSI: </span><span style=\" color:#ffff00;\">!!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Q1.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Q1</span></p><p align=\"center\"><span style=\" font-weight:600;\">FSR: </span><span style=\" color:#ffff00;\">!!v</span></p><p align=\"center\"><span style=\" font-weight:600;\">LSO: </span><span style=\" color:#ffff00;\">!!  </span><span style=\" font-weight:600;\">LSI: </span><span style=\" color:#ffff00;\">!!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Q3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Q3</span></p><p align=\"center\"><span style=\" font-weight:600;\">FSR: </span><span style=\" color:#ffff00;\">!!v</span></p><p align=\"center\"><span style=\" font-weight:600;\">LSO: </span><span style=\" color:#ffff00;\">!!  </span><span style=\" font-weight:600;\">LSI: </span><span style=\" color:#ffff00;\">!!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Q4.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Q4</span></p><p align=\"center\"><span style=\" font-weight:600;\">FSR: </span><span style=\" color:#ffff00;\">!!v</span></p><p align=\"center\"><span style=\" font-weight:600;\">LSO: </span><span style=\" color:#ffff00;\">!!  </span><span style=\" font-weight:600;\">LSI: </span><span style=\" color:#ffff00;\">!!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_internet.setText(QtGui.QApplication.translate("MainWindow", "Internet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_internetO.setText(QtGui.QApplication.translate("MainWindow", "!!internet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ros.setText(QtGui.QApplication.translate("MainWindow", "ROS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rosO.setText(QtGui.QApplication.translate("MainWindow", "!!rosmaster !!rosthread", None, QtGui.QApplication.UnicodeUTF8))
        self.label_charger.setText(QtGui.QApplication.translate("MainWindow", "Battery Charger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_chargerO.setText(QtGui.QApplication.translate("MainWindow", "!!chargerdevice", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mechanism.setText(QtGui.QApplication.translate("MainWindow", "Sandwich Mechanism", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mechanismO.setText(QtGui.QApplication.translate("MainWindow", "!!sandwichmechanism", None, QtGui.QApplication.UnicodeUTF8))
        self.label_drone.setText(QtGui.QApplication.translate("MainWindow", "Drone Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_droneO.setText(QtGui.QApplication.translate("MainWindow", "!!dronename", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dronebattery.setText(QtGui.QApplication.translate("MainWindow", "Drone Battery", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dronebatteryO.setText(QtGui.QApplication.translate("MainWindow", "!!dronebattery", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dronecell1.setText(QtGui.QApplication.translate("MainWindow", "Drone Cell", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dronecell1O.setText(QtGui.QApplication.translate("MainWindow", "!!dronecell1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dronecell2O.setText(QtGui.QApplication.translate("MainWindow", "!!dronecell2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dronecell3O.setText(QtGui.QApplication.translate("MainWindow", "!!cronecell3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_elapsed.setText(QtGui.QApplication.translate("MainWindow", "Elapsed Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_uptime.setText(QtGui.QApplication.translate("MainWindow", "Uptime", None, QtGui.QApplication.UnicodeUTF8))
        self.label_elapsedO.setText(QtGui.QApplication.translate("MainWindow", "!!elapsedtime", None, QtGui.QApplication.UnicodeUTF8))
        self.label_uptimeO.setText(QtGui.QApplication.translate("MainWindow", "!!uptime", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">!!status</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_network.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">!!hostname</p><p align=\"center\">!!macaddress</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.push_autostart.setText(QtGui.QApplication.translate("MainWindow", "Autostart", None, QtGui.QApplication.UnicodeUTF8))
        self.push_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.push_charge.setText(QtGui.QApplication.translate("MainWindow", "Charge", None, QtGui.QApplication.UnicodeUTF8))
        self.push_discharge.setText(QtGui.QApplication.translate("MainWindow", "Discharge", None, QtGui.QApplication.UnicodeUTF8))
        self.push_catch.setText(QtGui.QApplication.translate("MainWindow", "Catch", None, QtGui.QApplication.UnicodeUTF8))
        self.push_release.setText(QtGui.QApplication.translate("MainWindow", "Release", None, QtGui.QApplication.UnicodeUTF8))

